### ISSUE TITLE
why is working_directory mandatory?

### ISSUE THREAD

**Issue by antonkulaga** [peopledoc/mlvtools#81]
It is very annoying that it asks to specify a working directory all the time and in all commands. Can it just take the current directory (or the one in the config if I specified working directory explicitly there) if I do not specify it?

**Comment by elemoine** [comment]
@antonkulaga thanks for reaching out about this, and sorry for the delay responding. I created #87 to address the problem, where the working directory now defaults ".". Would that work for you?
